export const MSG = Object.freeze({
	// worker -> main
	READY: 'ready',
	SOURCE_INFO: 'source_info',
	SOURCE_ERROR: 'source_error',
	LOG: 'log',
	DONE: 'done',
	ERROR: 'error',
	DOWNLOAD_INIT: 'download_init',
	STREAM_CHUNK: 'stream_chunk',
	STREAM_CLOSE: 'stream_close',
	PAUSED: 'paused',
	CANCEL_ACK: 'cancel_ack',
	STREAM_INFO: 'stream_info',
	PROGRESS: 'progress',
	PARTITION_ITEM: 'partition_item',
	PARTITION_RESULT: 'partition_result',
	VERIFY_RESULT: 'verify_result',
	// main -> worker
	INSPECT: 'inspect',
	CONVERT: 'convert',
	DOWNLOAD_READY: 'download_ready',
	CHUNK_ACK: 'chunk_ack',
	PAUSE: 'pause',
	RESUME: 'resume',
	CANCEL: 'cancel',
	STREAM_READY: 'stream_ready',
	PARTITION_DIR: 'partition_dir',
	VERIFY_ORDER: 'verify_order',
	// main -> sw
	STREAM_REGISTER: 'stream_register',
	STREAM_ABORT: 'stream_abort',
	HEARTBEAT: 'heartbeat',
	// sw -> main
	REGISTERED: 'registered',
	CANCELLED: 'cancelled',
	STREAM_ATTACHED: 'stream_attached',
});

export const EVENTS = Object.freeze({
	SOURCE_ERROR: 'sourceerror',
	SOURCE_INFO: 'sourceinfo',
	CANCELLED: 'cancelled',
	ERROR: 'error',
	LOG: 'log',
	DONE: 'done',
	FEATURE_CHANGED: 'featurestatuschanged',
	PAUSED: 'paused',
	FILTER_CHANGED: 'filterchange',
	PROGRESS: 'progress',
	PARTITION_ITEM: 'partitionitem',
	PARTITION_RESULT: 'partitionresult',
	VERIFY_RESULT: 'verifyresult',
	QUEUE_ITEMS_ADDED: 'queueitemsadded',
});
