import crypto from 'node:crypto';

/**
 * Builds real, synthetic Xbox 360 keyvault buffers for e2e GoD-signing
 *
 * Certificate structure at CERTIFICATE_OFFSET ("Console Security
 * Certificate"): https://free60.org/System-Software/Formats/STFS/#signatures
 */

const EXPONENT_OFFSET = 0x29c;
const MODULUS_OFFSET = 0x2a8;
const MODULUS_LEN = 0x80; // 1024-bit console signing key
const PRIME_LEN = 0x40;
const PRIVATE_KEY_BLOCK_LEN = MODULUS_LEN + PRIME_LEN * 5; // n, p, q, dp, dq, qinv

export const CERTIFICATE_OFFSET = 0x9c8;
export const CERTIFICATE_LEN = 0x1a8;
export const KEYVAULT_LEN = CERTIFICATE_OFFSET + CERTIFICATE_LEN;

/**
 * Xbox 360 bignums are stored in the keyvault as a reversed sequence of
 * 8-byte qwords relative to plain big-endian - swaps qword `i` with qword
 * `N-1-i` in place. `reverseBytes` additionally flips the byte order
 * within each qword. Mutates `data` in place.
 *
 * @param {Uint8Array} data
 * @param {boolean} reverseBytes
 */
export function bnQwSwap(data, reverseBytes) {
	if (data.length % 8 !== 0) {
		throw new Error('bnQwSwap: length must be a multiple of 8');
	}
	const len = data.length;
	for (let i = 0; i < Math.floor(len / 2); i += 8) {
		for (let k = 0; k < 8; k++) {
			const a = i + k;
			const b = len - i - 8 + k;
			const tmp = data[a];
			data[a] = data[b];
			data[b] = tmp;
		}
	}
	if (reverseBytes) {
		for (let i = 0; i < len; i += 8) {
			for (let k = 0; k < 4; k++) {
				const a = i + k;
				const b = i + 7 - k;
				const tmp = data[a];
				data[a] = data[b];
				data[b] = tmp;
			}
		}
	}
}

/**
 * Left-pads `bytes` with zeros to exactly `len` bytes, for a JWK export
 * that comes back a byte short because the leading byte was zero.
 * @param {Uint8Array} bytes
 * @param {number} len
 * @returns {Uint8Array}
 */
function padLeft(bytes, len) {
	if (bytes.length === len) return bytes;
	if (bytes.length > len) {
		throw new Error(`padLeft: ${bytes.length} bytes doesn't fit in ${len}`);
	}
	const out = new Uint8Array(len);
	out.set(bytes, len - bytes.length);
	return out;
}

/**
 * @typedef {object} SyntheticKeyvault
 * @property {Uint8Array} kv - The full raw keyvault buffer.
 * @property {crypto.KeyObject} publicKey - The real RSA public key backing
 *   it, for verifying signatures produced with the corresponding signing
 *   key against a standard RSA verifier.
 * @property {Uint8Array} certificate - The 0x1A8-byte certificate blob
 *   embedded at CERTIFICATE_OFFSET, for asserting it round-trips
 *   byte-for-byte into a signed header/output.
 */

/**
 * Builds a synthetic keyvault buffer around a real 1024-bit RSA key
 * generated by Node's `crypto`, encoded the way the wasm module's
 * `core::signing::keyvault::ConsoleSigningKey::parse` expects to decode
 * it. Suitable for `setInputFiles()` against a `god-keyvault` file input.
 *
 * dp/dq/qinv are left zeroed: `parse()` derives everything it needs from
 * P/Q/exponent and never reads those fields.
 *
 * Calls into real RSA keygen, so prefer test-data.js's shared
 * `syntheticKeyvault` instance unless a test specifically needs a
 * second, distinct key (e.g. asserting per-item state doesn't leak
 * across two items each holding their own key).
 *
 * @returns {SyntheticKeyvault}
 */
export function makeSyntheticKeyvault() {
	const { publicKey, privateKey } = crypto.generateKeyPairSync('rsa', {
		modulusLength: 1024,
		publicExponent: 0x10001,
	});
	const jwk = /** @type {{ n: string, p: string, q: string }} */ (
		privateKey.export({ format: 'jwk' })
	);
	/** @param {string} b64url */
	const toBytes = (b64url) => new Uint8Array(Buffer.from(b64url, 'base64url'));
	const n = padLeft(toBytes(jwk.n), MODULUS_LEN);
	const p = padLeft(toBytes(jwk.p), PRIME_LEN);
	const q = padLeft(toBytes(jwk.q), PRIME_LEN);

	const kv = new Uint8Array(KEYVAULT_LEN);
	const view = new DataView(kv.buffer);
	view.setUint32(EXPONENT_OFFSET, 0x10001, false); // big-endian, matches from_be_bytes

	const block = new Uint8Array(PRIVATE_KEY_BLOCK_LEN);
	block.set(n, 0);
	block.set(p, MODULUS_LEN);
	block.set(q, MODULUS_LEN + PRIME_LEN);
	bnQwSwap(block.subarray(0, MODULUS_LEN), false);
	bnQwSwap(block.subarray(MODULUS_LEN, MODULUS_LEN + PRIME_LEN), false);
	bnQwSwap(
		block.subarray(MODULUS_LEN + PRIME_LEN, MODULUS_LEN + 2 * PRIME_LEN),
		false,
	);
	kv.set(block, MODULUS_OFFSET);

	// Filler pattern, not real X.509 bytes - the certificate is carried
	// through parse() verbatim, never parsed.
	const certificate = new Uint8Array(CERTIFICATE_LEN);
	for (let i = 0; i < CERTIFICATE_LEN; i++) certificate[i] = i & 0xff;
	kv.set(certificate, CERTIFICATE_OFFSET);

	return { kv, publicKey, certificate };
}

/**
 * Deliberately truncated keyvault (shorter than CERTIFICATE_OFFSET +
 * CERTIFICATE_LEN) - for exercising the UI's "invalid keyvault" error
 * path on the god-keyvault file input without needing a real device dump.
 *
 * @returns {Uint8Array}
 */
export function makeTruncatedKeyvault() {
	return crypto.getRandomValues(new Uint8Array(CERTIFICATE_OFFSET - 1));
}

/**
 * A correctly-sized keyvault buffer filled with random bytes - wrong
 * exponent, non-factoring modulus block, garbage certificate. For
 * exercising the "keyvault fails to parse/verify" error path as distinct
 * from the "too short" path covered by makeTruncatedKeyvault().
 *
 * @returns {Uint8Array}
 */
export function makeCorruptKeyvault() {
	return crypto.getRandomValues(new Uint8Array(KEYVAULT_LEN));
}
